<a href="https://colab.research.google.com/github/werowe/HypatiaAcademy/blob/master/class/2026_03_17_pandas_missing_data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# How to Clean Up Pandas Data

> *Video Tutorial*
>
> This tutorials is explained in depth in [this video](https://www.youtube.com/watch?v=6N_ncQjdcAU).

Here we should how to clean up Pandas data, in particular what do with about missing data, as well as what to do with invalid data.

Consider a survey.  If you send people a survey you cannot control in all cases what questions they will answer.  And you cannot anticipate what data they might put that is invalid.  For example, they might leave off some data.  Or they might enter a number in a question that is only supposed to be text.

So here we show you how to :

* generate some random data that is purposefully not clean
* drop duplicate rows
* get rid of rows that have missing values
* convert missing values to something else, like a fixed value of the average of all the other values in the colummn
* delete outliers, which are obvious typos.  For example, here we enter some salaries as 1 million while everyone else is around 100,000.  So that's most likely a mistake (since these are employees and not company owners or the CEO).
* apply a custom function to every row to do whatever special checking you want
* check for missing values
* show different ways to check for numbers or strings and how to convert those when they are of the wrong type

# Applications for Data (suitable for Pandas)


1.  cybersecurity.  kaspersky business.   feed windows events, firewall logs, database logins.  database could run out of space.  or password can expire.

2.  manufacturing.  FP missile.  machines.  vibration.  machine only works when calibrated.  a bolt or a screw or any piece of metal.  metal lathe.  carve it.  so you measure then temperature and vibration.  if it gets too hot.  machine is broken.  missile doesn't work.  have a truck.  100 trucks.  monitoring tire pressure.  brake temperature.  send all that data to your headquarters.  brakes are 400 C degrees.  sensor is broken.  it means the device that checks the temperature is broken.  that is data is outside normal distribution.

3.  cheating on tests in school.  If Yeremy gets a 2.  And George gets a 12.  And everyone sitting in Mrs, Jones class got a 12.  

4.  bank fraud.  someone takes out 4 million dollars.  and they only get paid 4,000.  freeze their account.

5.  survey.  a survey you send to people and you ask questions.  like 100 questions. like your health.  medical survey.  some will answer 10.  some will put letters where it's supposed to be numbers.  if you get a survey with 100 questions and 1 is missing.  do you throw away the survey?  no.


do you put a zero there?

maybe it's better to put the mean() value theren.  because if you zero it will skew the data for the population.


fred   40
john   50
sue    35
mary   0
walker *he won't say

40 + 50 + 35 + 0 + 0

125/5=21

40 + 50 + 35 + average + average

# Bad Data

Below we create some data and purposely add some bad data.  What do we do with this data?  Do we fix it? We we erase it?  Do we drop entire rows?  If this was a survey of 100 question you would not want to delete the rows because almost every person will either put bad data or not answer all questions.

In this data we have:

1. blank data in numeric columns
2. NaN (not a number) data in numeric columns
3. blank values in text columns
4. numbers that are multiple standard deviation away from the other answers, suggesting a type
5. Number in a Yes-No column

We will show how to clean up each.

In [3]:
import numpy as np
import pandas as pd

import random

def makedata():
  mean=10000
  std=25

  # this code creates random data.  It adds invalid and missing values to give us data to work with.

  cols = [("name", str), ("education", str),
     ("age", np.int8), ("city",str), ("id", np.int8), ("email", str), ("salary", np.int8),
        ("citizen", ["Y", "N"])]

  words = [np.nan, "", "abc", "def", "ghi", "jkl", "mno", "pqr"]

  records = []

  for i in range(20):

    data = {}

    for c in cols:

      if c[1] == np.int8:
        if random.randint(0,5)==5:
            data[c[0]] = np.nan
        else:
            data[c[0]] = abs(int(random.gauss(mean, std)))

      if c[0] == "citizen":
        if random.randint(0,5)==5:
            data[c[0]] = random.randint(0,10)
        else:
            data[c[0]] =c[1][random.randint(0,1)]

      if c[1] == str and c[0] != "citizen":
        data[c[0]] = words[random.randint(0,len(words)-1)]

      if (c[0] == "salary") & (random.randint(0,5)==0):
            data[c[0]] = 1000000

      if (c[0] == "age"):
          data[c[0]] = random.randint(20,25)

    records.append(data)

  df=pd.DataFrame(records)

  return df

df = makedata()
df

   name education  age city       id email     salary citizen
0   ghi       abc   25  pqr  10004.0   ghi     9974.0       N
1   pqr       ghi   25  mno  10015.0   ghi    10018.0       Y
2   abc             20  ghi  10013.0   jkl    10002.0       Y
3             jkl   20  mno  10031.0   jkl  1000000.0       Y
4   abc       ghi   22  jkl   9975.0   NaN     9999.0       Y
5   NaN       ghi   21  def  10010.0   abc    10013.0       N
6   def       abc   20  NaN      NaN   mno        NaN       Y
7   def       ghi   23  ghi   9969.0   abc        NaN       Y
8   ghi       ghi   21  ghi   9988.0   def    10001.0       N
9   ghi       NaN   23  pqr  10000.0   jkl    10000.0       Y
10  jkl       def   23  NaN  10014.0   NaN  1000000.0       Y
11            pqr   21  pqr      NaN   abc     9998.0       N
12            ghi   23  jkl      NaN              NaN       Y
13            ghi   22  mno   9997.0   def    10005.0       N
14  mno       jkl   25  def   9951.0   NaN     9968.0       N
15  jkl       NaN   21  abc  10030.0   pqr        NaN       N
16  jkl       mno   24  jkl  10014.0   NaN     9977.0       N
17  pqr       jkl   21  jkl   9998.0   NaN        NaN       Y
18  jkl       mno   24  pqr  10045.0   def    10007.0       Y
19  mno       ghi   24  mno      NaN   ghi    10020.0       Y

#Correlation


We are doing to do linear and logistic regression in the new few weeks.   This predicts values.

You can probable predict someone's salary based upon their education and their age.  

is education and age correlated salary.  yes.  because people with university make more.  and also older people.

# picky

# difficult to please

In [ ]:
# check if column in series is empty

# logical expression

df['name'].isnull()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11     True
12    False
13    False
14    False
15     True
16    False
17    False
18    False
19    False
Name: name, dtype: bool

In [9]:
df['is_blank_name']=df['name'].isnull()

In [10]:
df.drop("name", inplace=True)

,name,education,age,city,id,email,salary,citizen,is_blank,is_blank_name
0,ghi,abc,25,pqr,10004.0,ghi,9974.0,N,False,False
1,pqr,ghi,25,mno,10015.0,ghi,10018.0,Y,False,False
2,abc,,20,ghi,10013.0,jkl,10002.0,Y,False,False
3,,jkl,20,mno,10031.0,jkl,1000000.0,Y,False,False
4,abc,ghi,22,jkl,9975.0,NaN,9999.0,Y,False,False
5,NaN,ghi,21,def,10010.0,abc,10013.0,N,True,True
6,def,abc,20,NaN,NaN,mno,NaN,Y,False,False
7,def,ghi,23,ghi,9969.0,abc,NaN,Y,False,False
8,ghi,ghi,21,ghi,9988.0,def,10001.0,N,False,False
9,ghi,NaN,23,pqr,10000.0,jkl,10000.0,Y,False,False
10,jkl,def,23,NaN,10014.0,NaN,1000000.0,Y,False,False
11,,pqr,21,pqr,NaN,abc,9998.0,N,False,False
12,,ghi,23,jkl,NaN,,NaN,Y,False,False
13,,ghi,22,mno,9997.0,def,10005.0,N,False,False
14,mno,jkl,25,def,9951.0,NaN,9968.0,N,False,False
15,jkl,NaN,21,abc,10030.0,pqr,NaN,N,False,False
16,jkl,mno,24,jkl,10014.0,NaN,9977.0,N,False,False
17,pqr,jkl,21,jkl,9998.0,NaN,NaN,Y,False,False
18,jkl,mno,24,pqr,10045.0,def,10007.0,Y,False,False
19,mno,ghi,24,mno,NaN,ghi,10020.0,Y,False,False

In [20]:
# many pandas functions make a new dataframe
# so many offer option inplace=True
# otherwise you have to do this

df.drop("is_blank", axis=1, inplace=True)

In [14]:
df

,name,education,age,city,id,email,salary,citizen,is_blank,is_blank_name
0,ghi,abc,25,pqr,10004.0,ghi,9974.0,N,False,False
1,pqr,ghi,25,mno,10015.0,ghi,10018.0,Y,False,False
2,abc,,20,ghi,10013.0,jkl,10002.0,Y,False,False
3,,jkl,20,mno,10031.0,jkl,1000000.0,Y,False,False
4,abc,ghi,22,jkl,9975.0,NaN,9999.0,Y,False,False
5,NaN,ghi,21,def,10010.0,abc,10013.0,N,True,True
6,def,abc,20,NaN,NaN,mno,NaN,Y,False,False
7,def,ghi,23,ghi,9969.0,abc,NaN,Y,False,False
8,ghi,ghi,21,ghi,9988.0,def,10001.0,N,False,False
9,ghi,NaN,23,pqr,10000.0,jkl,10000.0,Y,False,False
10,jkl,def,23,NaN,10014.0,NaN,1000000.0,Y,False,False
11,,pqr,21,pqr,NaN,abc,9998.0,N,False,False
12,,ghi,23,jkl,NaN,,NaN,Y,False,False
13,,ghi,22,mno,9997.0,def,10005.0,N,False,False
14,mno,jkl,25,def,9951.0,NaN,9968.0,N,False,False
15,jkl,NaN,21,abc,10030.0,pqr,NaN,N,False,False
16,jkl,mno,24,jkl,10014.0,NaN,9977.0,N,False,False
17,pqr,jkl,21,jkl,9998.0,NaN,NaN,Y,False,False
18,jkl,mno,24,pqr,10045.0,def,10007.0,Y,False,False
19,mno,ghi,24,mno,NaN,ghi,10020.0,Y,False,False

In [ ]:
# df.loc[logical expression, columns]

df.loc[df['name'].isnull(), :]

   name education  age city       id email  salary citizen
11  NaN       ghi   21  abc  10021.0           NaN       N
15  NaN       abc   24  abc   9965.0   pqr  9977.0       6

In [18]:
df.loc[df['email'].isnull()]

,name,education,age,city,id,email,salary,citizen,is_blank,is_blank_name
4,abc,ghi,22,jkl,9975.0,NaN,9999.0,Y,False,False
10,jkl,def,23,NaN,10014.0,NaN,1000000.0,Y,False,False
14,mno,jkl,25,def,9951.0,NaN,9968.0,N,False,False
16,jkl,mno,24,jkl,10014.0,NaN,9977.0,N,False,False
17,pqr,jkl,21,jkl,9998.0,NaN,NaN,Y,False,False

# What to do about missing data?


1.  is it important.  email employees.  yes.  so call the person get their number.

2. maybe delete.  but delete column or row.

3. George said delete row because we don't have email.  Email says you have won a million dollars.   that one we manually fix.

4.  column is not important like need age to predict salary and city keep in city.  if it's citizen.  we could delete the column. or we do nothing.

5.  worst thing.

6.  different surveys have different purposes.

7.  industrial machine monitoring need temperature but do you need employee who last cleaned?  maybe now.

8.  worst thing to do is to delete entire when one column is bad.

In [ ]:
# delete column.

df.drop(column name, inplace, axis=1)

In [ ]:
# delete row

HOMEWORK figure this out

df.drop(column name, inplace, axis=0)

# Good instructions

https://www.kaggle.com/code/alexisbcook/missing-values

In [22]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("yasserh/housing-prices-dataset")

print("Path to dataset files:", path)

Using Colab cache for faster access to the 'housing-prices-dataset' dataset.
Path to dataset files: /kaggle/input/housing-prices-dataset

In [24]:
!ls /kaggle/input/housing-prices-dataset

Housing.csv

In [25]:
df= pd.read_csv(path + "/Housing.csv")

In [29]:
df

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished
...,...,...,...,...,...,...,...,...,...,...,...,...,...
540,1820000,3000,2,1,1,yes,no,yes,no,no,2,no,unfurnished
541,1767150,2400,3,1,1,no,no,no,no,no,0,no,semi-furnished
542,1750000,3620,2,1,1,yes,no,no,no,no,0,no,unfurnished
543,1750000,2910,3,1,1,no,no,no,no,no,0,no,furnished
544,1750000,3850,3,1,2,yes,no,no,no,no,0,no,unfurnished

In [28]:
df.isna().any()

price               False
area                False
bedrooms            False
bathrooms           False
stories             False
mainroad            False
guestroom           False
basement            False
hotwaterheating     False
airconditioning     False
parking             False
prefarea            False
furnishingstatus    False
dtype: bool

In [ ]:
# format for lookup

df.loc[logical_expression, columns]

df[df[x] == logical expression]

Python is a wrapper for C

Java runs in a Java Virtual Machine

C code you can destroy your computer.

This why hackers write code in C because they can change memory.

In [ ]:
# Here we check if

(df.isna() | df.isnull())

     name  education    age   city     id  email  salary  citizen
0   False      False  False  False  False  False   False    False
1   False      False  False   True  False  False   False    False
2    True      False  False  False  False  False   False    False
3   False      False  False  False  False  False   False    False
4   False      False  False  False  False  False   False    False
5   False      False  False  False  False  False   False    False
6   False       True  False  False  False  False   False    False
7    True      False  False  False  False  False   False    False
8   False      False  False   True  False   True   False    False
9   False      False  False  False  False   True   False    False
10  False      False  False   True  False  False   False    False
11   True      False  False   True  False  False   False    False
12  False      False  False  False  False  False    True    False
13  False      False  False  False  False  False   False    False
14   True      False  False  False  False  False   False    False
15  False      False  False  False  False  False   False    False
16  False      False  False  False  False  False   False    False
17  False      False  False   True  False  False   False    False
18  False      False  False  False   True  False   False    False
19  False      False  False  False  False  False   False    False

In [ ]:
df.loc[df['name'].isnull(), :]

   name education  age city       id email  salary citizen
11  NaN       ghi   21  abc  10021.0           NaN       N
15  NaN       abc   24  abc   9965.0   pqr  9977.0       6

In [ ]:
df.loc[df['name'].isna(), :]

   name education  age city       id email  salary citizen
11  NaN       ghi   21  abc  10021.0           NaN       N
15  NaN       abc   24  abc   9965.0   pqr  9977.0       6

In [ ]:
# None is a Python primitive (an integer, a boolean) it means not an object

# np.Nan is an object

np.NaN == None

False

In [ ]:
None

In [ ]:
df['salary']

0       10009.0
1        9999.0
2       10009.0
3       10025.0
4        9996.0
5        9966.0
6        9998.0
7        9975.0
8        9997.0
9        9971.0
10    1000000.0
11       9972.0
12          NaN
13      10061.0
14      10008.0
15      10011.0
16      10026.0
17      10000.0
18      10019.0
19      10011.0
Name: salary, dtype: float64


What do with do with outliers


1, 2, 4, 999999999

If we set the outlier to be the average it will not change the average


1, 2, 4, 1.3


we don't to delete the outliers

outlier?  it means a large number of std aaway from the mean

In [ ]:
# draw from mean()
# we can use the mean() function on a series.  A series is one column.
# Then we can replace blank values with the mean.  This is logical.

In [ ]:
df['salary'].mean()

195620.75

In [ ]:
df['citizen']

0     N
1     Y
2     Y
3     N
4     N
5     N
6     Y
7     N
8     N
9     Y
10    N
11    Y
12    Y
13    Y
14    N
15    Y
16    N
17    N
18    N
19    Y
Name: citizen, dtype: object

In [ ]:
# Yes, No columns cannot contain numbers
# NaN is OK as we can get rid of it in a second step plus certain functions like mean()
# will ignore it.  coerce means convert to NaN on error

df['citizen'] = df['citizen'].apply(lambda x: x if x in ['Y', 'N'] else "")

df['citizen']

0     N
1     Y
2     Y
3     N
4     N
5     N
6     Y
7     N
8     N
9     Y
10    N
11    Y
12    Y
13    Y
14    N
15    Y
16    N
17    N
18    N
19    Y
Name: citizen, dtype: object

In [ ]:
df['salary']

0       10009.0
1        9999.0
2       10009.0
3       10025.0
4        9996.0
5        9966.0
6        9998.0
7        9975.0
8        9997.0
9        9971.0
10    1000000.0
11       9972.0
12          NaN
13      10061.0
14      10008.0
15      10011.0
16      10026.0
17      10000.0
18      10019.0
19      10011.0
Name: salary, dtype: float64

In [ ]:
mean

62108.05263157895

In [ ]:
def makeMean(col):

   col['salary']=mean

   return col


#I think this is making a new dataframe.  Quesiton is now to update the xisting dataframe
# can we use inplace=Trye

x=df.loc[abs(df['salary'] - mean) > 2 * std].apply(makeMean)

#Homework

Fix this.  It should have only updated the 3 rows and only the salary column.

In [ ]:
x

,name,education,age,city,id,email,salary,citizen
1,,NaN,20.000000,jkl,10000.000000,def,1000000.000000,N
5,ghi,jkl,21.000000,pqr,9994.000000,jkl,1000000.000000,N
17,jkl,def,20.000000,abc,9958.000000,NaN,1000000.000000,Y
salary,62108.052632,62108.052632,62108.052632,62108.052632,62108.052632,62108.052632,62108.052632,62108.052632

In [ ]:
x.index

Index([1, 5, 17, 'salary'], dtype='object')

In [ ]:
df

   name education  age city       id email     salary citizen
0   jkl       ghi   25  NaN   9997.0   NaN        NaN       N
1             NaN   20  jkl  10000.0   def  1000000.0       N
2   abc       ghi   22  pqr      NaN           9998.0       N
3   pqr       ghi   20        9994.0   pqr     9974.0       Y
4   ghi       abc   21  NaN   9974.0   pqr        NaN       N
5   ghi       jkl   21  pqr   9994.0   jkl  1000000.0       N
6   def       def   24  pqr  10003.0   pqr     9976.0       3
7   abc       jkl   22  pqr      NaN           9959.0       Y
8   def       ghi   25  abc  10049.0   mno     9988.0       N
9                   23       10019.0   abc    10003.0       N
10  def       def   22  NaN      NaN          10040.0       Y
11  NaN       ghi   21  abc  10021.0              NaN       N
12  jkl       NaN   25  NaN   9985.0   jkl     9979.0       N
13  mno       def   21  jkl      NaN   NaN     9977.0       Y
14            ghi   25  def   9968.0   NaN        NaN       Y
15  NaN       abc   24  abc   9965.0   pqr     9977.0       6
16  pqr       NaN   24  pqr   9992.0   jkl    10018.0       N
17  jkl       def   20  abc   9958.0   NaN  1000000.0       Y
18  pqr       def   24        9979.0   mno    10026.0       Y
19            jkl   20  jkl  10016.0   pqr    10017.0       N

In [ ]:
# drop outliers, too many standard deviations away
# if the income - mean > 2 std the replace then drop the row
# remeber to use inplace=True


mean = df['salary'].mean()
std = df['salary'].std()

# Define threshold for outliers (e.g., values more than 2 standard deviations away from the mean)
threshold = 2

# calculate
# find with .loc
# drop
# inplace=True


df.drop(df.loc[abs(df['salary'] - mean) > 2 * std].index, inplace=True)

df

   name education  age city       id email   salary citizen
0   ghi       abc   22  ghi  10027.0   def  10009.0       N
1   ghi       pqr   21  NaN   9986.0   abc   9999.0       Y
2   NaN       jkl   23  abc  10028.0   mno  10009.0       Y
3   jkl       jkl   22  pqr  10043.0   abc  10025.0       N
4   ghi       mno   20  jkl   9980.0   ghi   9996.0       N
5   mno       jkl   21  def   9992.0   mno   9966.0       N
6             NaN   21  pqr   9994.0   pqr   9998.0       Y
7   NaN       jkl   24  mno  10017.0   mno   9975.0       N
8   ghi       def   23  NaN   9983.0   NaN   9997.0       N
9   jkl       jkl   23  mno   9981.0   NaN   9971.0       Y
11  NaN       ghi   25  NaN   9995.0   mno   9972.0       Y
12  jkl       def   22  def  10008.0            NaN       Y
13  def             23  def  10012.0   jkl  10061.0       Y
14  NaN       def   20        9980.0   def  10008.0       N
15                  23  pqr   9969.0   pqr  10011.0       Y
16  abc       jkl   20  abc   9997.0        10026.0       N
17  jkl             24  NaN   9994.0   def  10000.0       N
18            ghi   25  pqr      NaN   pqr  10019.0       N
19  jkl       pqr   25  abc  10021.0        10011.0       Y

In [ ]:
abs(1000000 - mean) > 2 * std

True

In [ ]:
mean

62108.05263157895

In [ ]:
std

227120.90214672344

In [ ]:
sMean=df['salary'].mean()

# this will replace missing values with the mean

df['salary'] = df['salary'].fillna(sMean)

df

   name education  age city       id email        salary citizen
0   ghi       abc   22  ghi  10027.0   def  10009.000000       N
1   ghi       pqr   21  NaN   9986.0   abc   9999.000000       Y
2   NaN       jkl   23  abc  10028.0   mno  10009.000000       Y
3   jkl       jkl   22  pqr  10043.0   abc  10025.000000       N
4   ghi       mno   20  jkl   9980.0   ghi   9996.000000       N
5   mno       jkl   21  def   9992.0   mno   9966.000000       N
6             NaN   21  pqr   9994.0   pqr   9998.000000       Y
7   NaN       jkl   24  mno  10017.0   mno   9975.000000       N
8   ghi       def   23  NaN   9983.0   NaN   9997.000000       N
9   jkl       jkl   23  mno   9981.0   NaN   9971.000000       Y
11  NaN       ghi   25  NaN   9995.0   mno   9972.000000       Y
12  jkl       def   22  def  10008.0        10002.944444       Y
13  def             23  def  10012.0   jkl  10061.000000       Y
14  NaN       def   20        9980.0   def  10008.000000       N
15                  23  pqr   9969.0   pqr  10011.000000       Y
16  abc       jkl   20  abc   9997.0        10026.000000       N
17  jkl             24  NaN   9994.0   def  10000.000000       N
18            ghi   25  pqr      NaN   pqr  10019.000000       N
19  jkl       pqr   25  abc  10021.0        10011.000000       Y

In [ ]:
# drop all numbers in Yes/No answer

df['citizen'] = df['citizen'].apply(lambda x: x if isinstance(x,str) else np.NaN)
df['citizen']

0     N
1     Y
2     Y
3     N
4     N
5     N
6     Y
7     N
8     N
9     Y
11    Y
12    Y
13    Y
14    N
15    Y
16    N
17    N
18    N
19    Y
Name: citizen, dtype: object

In [ ]:
# Here is how to drop all rows that have any NaN values in any column.
# we will leave off inplace=True so that we don't delete all the data that we need for this lesson.
# remember that if you don't put inplace=True and you have not assigned the df.somefunction() to
# some value then you have effectively done nothing as nothing has changed

df.dropna(how='any')
df

   name education  age city       id email        salary citizen
0   ghi       abc   22  ghi  10027.0   def  10009.000000       N
1   ghi       pqr   21  NaN   9986.0   abc   9999.000000       Y
2   NaN       jkl   23  abc  10028.0   mno  10009.000000       Y
3   jkl       jkl   22  pqr  10043.0   abc  10025.000000       N
4   ghi       mno   20  jkl   9980.0   ghi   9996.000000       N
5   mno       jkl   21  def   9992.0   mno   9966.000000       N
6             NaN   21  pqr   9994.0   pqr   9998.000000       Y
7   NaN       jkl   24  mno  10017.0   mno   9975.000000       N
8   ghi       def   23  NaN   9983.0   NaN   9997.000000       N
9   jkl       jkl   23  mno   9981.0   NaN   9971.000000       Y
11  NaN       ghi   25  NaN   9995.0   mno   9972.000000       Y
12  jkl       def   22  def  10008.0        10002.944444       Y
13  def             23  def  10012.0   jkl  10061.000000       Y
14  NaN       def   20        9980.0   def  10008.000000       N
15                  23  pqr   9969.0   pqr  10011.000000       Y
16  abc       jkl   20  abc   9997.0        10026.000000       N
17  jkl             24  NaN   9994.0   def  10000.000000       N
18            ghi   25  pqr      NaN   pqr  10019.000000       N
19  jkl       pqr   25  abc  10021.0        10011.000000       Y

In [ ]:
# here run a function on a Pandas series, which is a single column.  But since we are
# sending a single row-column combination we can work with it as we would with any
# Python primitive (meaning built-in type.  Pandas and Numpy are extension of Python into new types.)
# In the next example we show how to work with an entire row, where we have all columns we can work with


def toUpper(s):
    if isinstance(s,str):
      return s.upper()


df['city']=df['city'].apply(toUpper)
df

   name education  age  city       id email        salary citizen
0   ghi       abc   22   GHI  10027.0   def  10009.000000       N
1   ghi       pqr   21  None   9986.0   abc   9999.000000       Y
2   NaN       jkl   23   ABC  10028.0   mno  10009.000000       Y
3   jkl       jkl   22   PQR  10043.0   abc  10025.000000       N
4   ghi       mno   20   JKL   9980.0   ghi   9996.000000       N
5   mno       jkl   21   DEF   9992.0   mno   9966.000000       N
6             NaN   21   PQR   9994.0   pqr   9998.000000       Y
7   NaN       jkl   24   MNO  10017.0   mno   9975.000000       N
8   ghi       def   23  None   9983.0   NaN   9997.000000       N
9   jkl       jkl   23   MNO   9981.0   NaN   9971.000000       Y
11  NaN       ghi   25  None   9995.0   mno   9972.000000       Y
12  jkl       def   22   DEF  10008.0        10002.944444       Y
13  def             23   DEF  10012.0   jkl  10061.000000       Y
14  NaN       def   20         9980.0   def  10008.000000       N
15                  23   PQR   9969.0   pqr  10011.000000       Y
16  abc       jkl   20   ABC   9997.0        10026.000000       N
17  jkl             24  None   9994.0   def  10000.000000       N
18            ghi   25   PQR      NaN   pqr  10019.000000       N
19  jkl       pqr   25   ABC  10021.0        10011.000000       Y

In [ ]:
# axis = 1 means row
# axis = 0 means column

# the important point to note there is we send the entire row in as a paramters. thus all the columns
# are available to use.  remember to send back the entire row after you have updated any of the columns.

def wholeRow(row):
  if isinstance(row['city'],str):
     row['city'] = row['city'].lower()
     return row


df=df.apply(wholeRow, axis=1)
df

    name education   age  city       id email        salary citizen
0    ghi       abc  22.0   ghi  10027.0   def  10009.000000       N
1   None      None   NaN  None      NaN  None           NaN    None
2    NaN       jkl  23.0   abc  10028.0   mno  10009.000000       Y
3    jkl       jkl  22.0   pqr  10043.0   abc  10025.000000       N
4    ghi       mno  20.0   jkl   9980.0   ghi   9996.000000       N
5    mno       jkl  21.0   def   9992.0   mno   9966.000000       N
6              NaN  21.0   pqr   9994.0   pqr   9998.000000       Y
7    NaN       jkl  24.0   mno  10017.0   mno   9975.000000       N
8   None      None   NaN  None      NaN  None           NaN    None
9    jkl       jkl  23.0   mno   9981.0   NaN   9971.000000       Y
11  None      None   NaN  None      NaN  None           NaN    None
12   jkl       def  22.0   def  10008.0        10002.944444       Y
13   def            23.0   def  10012.0   jkl  10061.000000       Y
14   NaN       def  20.0         9980.0   def  10008.000000       N
15                  23.0   pqr   9969.0   pqr  10011.000000       Y
16   abc       jkl  20.0   abc   9997.0        10026.000000       N
17  None      None   NaN  None      NaN  None           NaN    None
18             ghi  25.0   pqr      NaN   pqr  10019.000000       N
19   jkl       pqr  25.0   abc  10021.0        10011.000000       Y

# Eliminate Duplicates

Here we show how to get rid of duplicate rows.

In [ ]:
df = pd.DataFrame({
    "a" : [1,2,3,3,3,3,5,6,7,7,7,7]
})

df.groupby('a')['a'].count()

a
1    1
2    1
3    4
5    1
6    1
7    4
Name: a, dtype: int64

In [ ]:
df.value_counts()

a
3    4
7    4
1    1
2    1
5    1
6    1
Name: count, dtype: int64

In [ ]:
# we need to get rid of duplicates



df.drop_duplicates(inplace=True)
df.groupby('a')['a'].count()

a
1    1
2    1
3    1
5    1
6    1
7    1
Name: a, dtype: int64

In [ ]:
df['a'].value_counts()

a
1    1
2    1
3    1
5    1
6    1
7    1
Name: count, dtype: int64

In [ ]:
df = makedata()

df.groupby('age')['age'].count()

age
20    2
21    1
22    4
23    3
24    2
25    8
Name: age, dtype: int64

In [ ]:
# keep='first' Mark duplicates as True except for the first occurrence

df['duplicate'] = df.duplicated(subset=['age'], keep='first')

df.sort_values("age")

   name education  age city       id email     salary citizen  duplicate
0   ghi       pqr   20  ghi  10022.0   abc    10035.0       Y      False
17  def             20  ghi  10036.0   jkl    10032.0       N       True
19  mno       def   21  def   9999.0   abc  1000000.0       Y      False
3   NaN       mno   22  jkl  10038.0   jkl    10009.0       N       True
7   ghi       jkl   22  NaN  10001.0   mno  1000000.0       1       True
14  mno       pqr   22  NaN  10035.0           9948.0       1       True
2   def       ghi   22           NaN   NaN     9986.0       9      False
1             NaN   23  mno  10037.0   ghi    10002.0       4      False
18  def       def   23  mno  10015.0   mno     9999.0       5       True
12  jkl       mno   23  NaN   9993.0   NaN    10019.0       3       True
6   pqr       NaN   24       10015.0   abc    10019.0       Y      False
13  ghi       ghi   24  mno      NaN   abc    10011.0       N       True
16  jkl       jkl   25  NaN  10032.0   ghi        NaN       Y       True
15  mno       NaN   25  pqr      NaN   pqr        NaN       Y       True
11  NaN             25  pqr  10027.0   def     9995.0       N       True
8   ghi       NaN   25  pqr   9977.0   jkl    10014.0       N       True
5   jkl       abc   25  pqr      NaN   jkl  1000000.0       N       True
4   NaN       abc   25  def   9983.0   NaN     9990.0       N      False
10  mno       mno   25  abc   9994.0           9972.0       2       True
9   NaN       pqr   25  ghi  10031.0   abc    10055.0       N       True

In [ ]:
# drop those where duplicate is true.  Notice the gap in index values show which rows were dropped

df=df[df['duplicate'] == False]

In [ ]:
df.sort_values("age")

   name education  age city       id email     salary citizen  duplicate
0   ghi       pqr   20  ghi  10022.0   abc    10035.0       Y      False
19  mno       def   21  def   9999.0   abc  1000000.0       Y      False
2   def       ghi   22           NaN   NaN     9986.0       9      False
1             NaN   23  mno  10037.0   ghi    10002.0       4      False
6   pqr       NaN   24       10015.0   abc    10019.0       Y      False
4   NaN       abc   25  def   9983.0   NaN     9990.0       N      False

#Homework

See if you can find any data on the internet that has missing values.

And look at the housing dataset above and find out if there is any rows with missing data.