<a href="https://colab.research.google.com/github/werowe/HypatiaAcademy/blob/master/class/20260_03_20_dirty_data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [69]:
import pandas as pd

df = pd.read_csv("https://raw.githubusercontent.com/werowe/HypatiaAcademy/refs/heads/master/ml/dirty_cafe_sales.csv")

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    10000 non-null  object
 1   Item              9667 non-null   object
 2   Quantity          9862 non-null   object
 3   Price Per Unit    9821 non-null   object
 4   Total Spent       9827 non-null   object
 5   Payment Method    7421 non-null   object
 6   Location          6735 non-null   object
 7   Transaction Date  9841 non-null   object
dtypes: object(8)
memory usage: 625.1+ KB

In [70]:
df

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11
...,...,...,...,...,...,...,...,...
9995,TXN_7672686,Coffee,2,2.0,4.0,NaN,UNKNOWN,2023-08-30
9996,TXN_9659401,NaN,3,NaN,3.0,Digital Wallet,NaN,2023-06-02
9997,TXN_5255387,Coffee,4,2.0,8.0,Digital Wallet,NaN,2023-03-02
9998,TXN_7695629,Cookie,3,NaN,3.0,Digital Wallet,NaN,2023-12-02
9999,TXN_6170729,Sandwich,3,4.0,12.0,Cash,In-store,2023-11-07

In [73]:
df.set_index("Transaction ID", inplace=True)

In [74]:
df

,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
Transaction ID,,,,,,,
TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11
...,...,...,...,...,...,...,...
TXN_7672686,Coffee,2,2.0,4.0,NaN,UNKNOWN,2023-08-30
TXN_9659401,NaN,3,NaN,3.0,Digital Wallet,NaN,2023-06-02
TXN_5255387,Coffee,4,2.0,8.0,Digital Wallet,NaN,2023-03-02
TXN_7695629,Cookie,3,NaN,3.0,Digital Wallet,NaN,2023-12-02
TXN_6170729,Sandwich,3,4.0,12.0,Cash,In-store,2023-11-07

In [75]:
# cast a  value to a number

#df['Total Spent'], errors='coerce')

j = "3"

3 * j

# concatenate

'333'

In [76]:
3 * int(j)

9

In [77]:
float(j)

3.0

In [82]:
import numpy as np


# take 3.5 and conver it to a 8 integer


1111 1111

11<----memory 1111 1111



np.array(2570).astype(np.int8)

array(10, dtype=int8)

In [88]:
pd.to_numeric(df['Total Spent'], errors='coerce').isna()

Transaction ID
TXN_1961373    False
TXN_4977031    False
TXN_4271903     True
TXN_7034554    False
TXN_3160411    False
               ...
TXN_7672686    False
TXN_9659401    False
TXN_5255387    False
TXN_7695629    False
TXN_6170729    False
Name: Total Spent, Length: 10000, dtype: bool

In [84]:
df.iloc[0]['Total Spent']

'4.0'

In [91]:
# turns into np.NaN if it cannot be converred to number

bad = pd.to_numeric(df['Total Spent'], errors='coerce').isna()


#df.loc[logical expression]

l = ['TXN_4271903']
df.loc[l]

df.loc[bad]

,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
Transaction ID,,,,,,,
TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
TXN_7958992,Smoothie,3,4.0,NaN,UNKNOWN,UNKNOWN,2023-12-13
TXN_8927252,UNKNOWN,2,1.0,ERROR,Credit Card,ERROR,2023-11-06
TXN_6650263,Tea,2,1.5,UNKNOWN,NaN,Takeaway,2023-01-10
TXN_4987129,Sandwich,3,NaN,NaN,NaN,In-store,2023-10-20
...,...,...,...,...,...,...,...
TXN_3809533,Juice,2,NaN,ERROR,Digital Wallet,Takeaway,2023-02-02
TXN_1191659,Coffee,4,2.0,ERROR,Credit Card,In-store,2023-11-21
TXN_5548914,Juice,2,3.0,ERROR,Digital Wallet,In-store,2023-11-04
TXN_9594133,Cake,5,3.0,NaN,ERROR,NaN,NaN
TXN_4766549,Smoothie,2,4.0,NaN,Cash,NaN,2023-10-20

In [39]:

# ñ tilde means not

df.loc[~bad]

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11
5,TXN_2602893,Smoothie,5,4.0,20.0,Credit Card,NaN,2023-03-31
...,...,...,...,...,...,...,...,...
9995,TXN_7672686,Coffee,2,2.0,4.0,NaN,UNKNOWN,2023-08-30
9996,TXN_9659401,NaN,3,NaN,3.0,Digital Wallet,NaN,2023-06-02
9997,TXN_5255387,Coffee,4,2.0,8.0,Digital Wallet,NaN,2023-03-02
9998,TXN_7695629,Cookie,3,NaN,3.0,Digital Wallet,NaN,2023-12-02
9999,TXN_6170729,Sandwich,3,4.0,12.0,Cash,In-store,2023-11-07

In [40]:
bad = pd.to_numeric(df['Quantity'], errors='coerce').isna()

df.loc[bad]

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
20,TXN_3522028,Smoothie,ERROR,4.0,20.0,Cash,In-store,2023-04-04
55,TXN_5522862,Cookie,ERROR,1.0,2.0,Credit Card,Takeaway,2023-03-19
57,TXN_2080895,Cake,UNKNOWN,3.0,3.0,Digital Wallet,In-store,2023-04-19
66,TXN_8501819,Juice,NaN,3.0,6.0,Cash,NaN,2023-03-30
117,TXN_2148617,Juice,ERROR,3.0,9.0,Digital Wallet,UNKNOWN,2023-01-10
...,...,...,...,...,...,...,...,...
9932,TXN_8502079,Tea,UNKNOWN,1.5,3.0,Cash,NaN,2023-04-20
9935,TXN_9778251,Tea,ERROR,1.5,6.0,NaN,Takeaway,2023-11-09
9944,TXN_7495283,Cake,UNKNOWN,3.0,15.0,Credit Card,Takeaway,2023-04-14
9957,TXN_6487003,Coffee,ERROR,2.0,8.0,Credit Card,Takeaway,2023-11-15
9984,TXN_3142496,Smoothie,UNKNOWN,4.0,4.0,Cash,Takeaway,2023-07-27

In [92]:
# find outliers.  that means far away from everyone else


bad = pd.to_numeric(df['Quantity'], errors='coerce').isna()

good=df.loc[~bad]

std=good['Quantity'].astype(int).std()
mean=good['Quantity'].astype(int).std()

In [93]:
std, mean

(1.4190068732212457, 1.4190068732212457)

In [94]:
good['Quantity'].describe()

count     9521
unique       5
top          5
freq      2013
Name: Quantity, dtype: object

In [48]:
good['Quantity'].astype(int).describe()

count    9521.000000
mean        3.028463
std         1.419007
min         1.000000
25%         2.000000
50%         3.000000
75%         4.000000
max         5.000000
Name: Quantity, dtype: float64

In [55]:

# 32 * 1 1 std


good['Quantity'] = pd.to_numeric(good['Quantity'], errors='coerce')


std = good['Quantity'].std()

good.loc[good['Quantity'] > 2 * std]

/tmp/ipykernel_3927/2492571576.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  good['Quantity'] = pd.to_numeric(good['Quantity'], errors='coerce')

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
5,TXN_2602893,Smoothie,5,4.0,20.0,Credit Card,NaN,2023-03-31
6,TXN_4433211,UNKNOWN,3,3.0,9.0,ERROR,Takeaway,2023-10-06
7,TXN_6699534,Sandwich,4,4.0,16.0,Cash,UNKNOWN,2023-10-28
...,...,...,...,...,...,...,...,...
9994,TXN_7851634,UNKNOWN,4,4.0,16.0,NaN,NaN,2023-01-08
9996,TXN_9659401,NaN,3,NaN,3.0,Digital Wallet,NaN,2023-06-02
9997,TXN_5255387,Coffee,4,2.0,8.0,Digital Wallet,NaN,2023-03-02
9998,TXN_7695629,Cookie,3,NaN,3.0,Digital Wallet,NaN,2023-12-02
9999,TXN_6170729,Sandwich,3,4.0,12.0,Cash,In-store,2023-11-07

In [57]:
df[df.duplicated()]

Empty DataFrame
Columns: [Transaction ID, Item, Quantity, Price Per Unit, Total Spent, Payment Method, Location, Transaction Date]
Index: []

In [60]:
df.groupby("Item").count()

,Transaction ID,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
Item,,,,,,,
Cake,1139,1121,1118,1120,855,767,1122
Coffee,1165,1146,1146,1149,816,750,1151
Cookie,1092,1075,1068,1073,829,762,1071
ERROR,292,287,285,285,213,197,289
Juice,1171,1158,1154,1159,903,769,1161
Salad,1148,1135,1132,1129,868,790,1131
Sandwich,1131,1113,1114,1105,822,793,1114
Smoothie,1096,1086,1072,1078,816,712,1074
Tea,1089,1076,1069,1064,792,743,1064
UNKNOWN,344,335,337,336,256,223,337

In [64]:
 df[df['Item'].isin(['UNKNOWN', 'ERROR'])]

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
6,TXN_4433211,UNKNOWN,3,3.0,9.0,ERROR,Takeaway,2023-10-06
14,TXN_8915701,ERROR,2,1.5,3.0,NaN,In-store,2023-03-21
31,TXN_8927252,UNKNOWN,2,1.0,ERROR,Credit Card,ERROR,2023-11-06
33,TXN_7710508,UNKNOWN,5,1.0,5.0,Cash,NaN,ERROR
36,TXN_6855453,UNKNOWN,4,3.0,12.0,NaN,In-store,2023-07-17
...,...,...,...,...,...,...,...,...
9946,TXN_8807600,UNKNOWN,1,4.0,4.0,Cash,Takeaway,2023-09-24
9951,TXN_4122925,ERROR,4,1.0,4.0,NaN,Takeaway,2023-10-20
9958,TXN_4125474,ERROR,2,5.0,10.0,Credit Card,In-store,2023-08-02
9981,TXN_4583012,ERROR,5,4.0,20.0,Digital Wallet,NaN,2023-02-27
9994,TXN_7851634,UNKNOWN,4,4.0,16.0,NaN,NaN,2023-01-08

In [68]:
df['Total Spent'] = pd.to_numeric(good['Total Spent'], errors='coerce')


q1 = df['Total Spent'].quantile(0.25)
q3 = df['Total Spent'].quantile(0.75)
iqr = q3 - q1
outliers = df[(df['Total Spent'] < q1 - 1.5*iqr) |
              (df['Total Spent'] > q3 + 1.5*iqr)]

outliers

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
10,TXN_2548360,Salad,5,5.0,25.0,Cash,Takeaway,2023-11-07
51,TXN_6342161,Salad,5,5.0,25.0,ERROR,Takeaway,2023-01-08
52,TXN_8914892,UNKNOWN,5,5.0,25.0,Digital Wallet,NaN,2023-03-15
96,TXN_5220895,Salad,5,5.0,25.0,Cash,In-store,2023-06-10
100,TXN_9517146,NaN,5,5.0,25.0,Cash,Takeaway,2023-10-30
...,...,...,...,...,...,...,...,...
9791,TXN_1232346,Salad,5,5.0,25.0,Digital Wallet,In-store,2023-01-04
9805,TXN_9506076,Salad,5,5.0,25.0,NaN,NaN,2023-01-17
9879,TXN_6393305,Salad,5,5.0,25.0,Digital Wallet,In-store,2023-10-19
9908,TXN_8922585,Salad,5,5.0,25.0,Credit Card,UNKNOWN,2023-06-22
9971,TXN_6120851,Salad,5,5.0,25.0,Cash,Takeaway,2023-02-04

In [ ]:
# Load clean California housing + add realistic missing values (15% like real datasets)
print("Loading housing data...")
data = fetch_california_housing()
df = pd.DataFrame(data.data, columns=data.feature_names)
df['Price'] = data.target  # Add target column

# Create "bad data" with missing values (your homework requirement)
np.random.seed(42)
missing_cols = ['MedInc', 'HouseAge', 'AveRooms', 'Population']
for col in missing_cols:
    missing_mask = np.random.choice(df.index, size=int(len(df)*0.15), replace=False)
    df.loc[missing_mask, col] = np.nan

print("✅ Dataset created with missing values!")
print(f"Shape: {df.shape}")
print("\nMissing values per column:")
missing_count = df.isnull().sum()
print(missing_count[missing_count > 0])